### ISSUE TITLE
non-blocking socket could not be completed immediately cHttpRequest

### ISSUE THREAD

**Issue by surfer-silver** [wqweto/VbAsyncSocket#48]
test project Basic raises this error in latest release

**Comment by surfer-silver** [comment]
My mistake ... it is for [HTTP Request] Sir... i tried your example manipulated but same ... but [cTlsSocketHTTPS] working ok for trying to connect with https://ipinfo.io

**Comment by wqweto** [comment]
Can you prepare a failing project?

I'm testing with latest `HttpRequest.dll` this code
```
Option Explicit

Private Sub Form_Load()
    With New cHttpRequest
        .Open_ "GET", "https://ipinfo.io/json"
        .Send
        Debug.Print .ResponseText
    End With
End Sub
```
... and it works here.

Try downloading and testing with latest [HttpRequest.zip](https://github.com/wqweto/VbAsyncSocket/releases/download/HRR-1.0.6/HttpRequest.zip) from **Releases** section.

**Comment by surfer-silver** [comment]
tested with cHttpRequest class in Basic sample project

**Comment by wqweto** [comment]
Ok, I just changed Command2 event Click to this
```
Private Sub Command2_Click()
    With New cHttpRequest
        .Open_ "GET", "https://ipinfo.io/json"
        .Send
        Debug.Print .ResponseText
    End With
End Sub
```
. . . and it works here.

**Comment by surfer-silver** [comment]
i already did this..
but again i download sourcecode...  removed previous extract 
change as per above and boom same error here is the conditional 
ASYNCSOCKET_NO_TLSSERVER = 1 : USE_DEBUG_LOG = 1 : USE_TLS = 1 : Dummy = 1
see screen shot
![image](https://github.com/wqweto/VbAsyncSocket/assets/99076074/e78b8020-4b88-4e5c-8b1a-769493f9e0e6)

**Comment by wqweto** [comment]
Can you put a breakpoint on `cHttpRequest.pvSetError` method and when it gets hit post screenshot of the call-stack dialog (Ctrl+L)?

**Comment by surfer-silver** [comment]
without changing anything screenshot 1
![image](https://github.com/wqweto/VbAsyncSocket/assets/99076074/a41e1da8-bde8-4a56-97ca-8844e1b0326a)

with other included locals too
![image](https://github.com/wqweto/VbAsyncSocket/assets/99076074/9e0f1b53-a636-427d-a636-d38e3602865d)

**Comment by wqweto** [comment]
Weird. It looks like you are not using the latest version of cHttpRequest.cls -- the code is currently different for [line 1337](https://github.com/wqweto/VbAsyncSocket/blob/master/contrib/cHttpRequest.cls#L1337) with the fix in commit 3935cfcb4823b30a2f1f0571facc683f8581afa3 I already mentioned above.

**Comment by surfer-silver** [comment]
running perfectly...  just downloaded the released version ... thought all changes merged in released version provided ... 
now lesson learned for future

if possible, please share your experience of using git hub with vb6 it will help so many people as you can see the result just because of github again thanks alot for such wonderfull code

**Comment by wqweto** [comment]
There are GUI clients like [GitHub Desktop](https://desktop.github.com/) or [Sourcetree](https://www.sourcetreeapp.com/) which make life easier in the beginning.
