### ISSUE TITLE
[Improvement] Reg-Free manifest

### ISSUE THREAD

**Issue by dragokas** [wqweto/VbAsyncSocket#6]
A little suggestion, - to add manifest sample in your project to remove a requirement for registration of winsock component, and subsequent requirement for run as admin.

![winsock](https://user-images.githubusercontent.com/19956568/92333770-b4f2f680-f090-11ea-9337-138658961ff5.png)

**Comment by wqweto** [comment]
Actually mswinsck.ocx reference in the test project is leftover from initial tests of replacement behavior against original control which is unnecessary as of now. I just removed the reference althogether.
