### ISSUE TITLE
[Improvement] More simple samples on separate Client-Server apps

### ISSUE THREAD

**Issue by dragokas** [wqweto/VbAsyncSocket#7]
Suggestion:

![client-server](https://user-images.githubusercontent.com/19956568/92444139-216a1480-f1bb-11ea-8dc0-9d198f4c32e1.jpg)

to have more minimalistic samples. Projects attached.
[Winsock-simple.zip](https://github.com/wqweto/VbAsyncSocket/files/5186637/Winsock-simple.zip)

Also, don't you mind to clarify:

1) do I correctly stop the connection:
```
Private Sub cmdStop_Click()
    Dim i&
    For i = 0 To ctxServer.UBound
        If Not (ctxServer(i) Is Nothing) Then
            ctxServer(i).Close_
        End If
    Next
```
2) Comparing to Chat\Project1.vbp sample, where user control is not used, what is a difference? Is that mean, it is not multithreaded, so some side-effects are expected?

Thank you.

**Comment by wqweto** [comment]
1. Yes, server stop looks ok. This will probably unload the control in `CloseEvent` too. (You can remove `Close` event impl as there is no `Close` event at all).
2. You don't need a Winsock control per se, it's a crutch for those familiar with VB6 provided one. You can directly use `cAsyncSocket` (or `cTlsSocket`) to establish socket connections

`cTlsSocket` is source-compatible with `cAsyncSocket` meaning that if some code is using plain TCP connections with `cAsyncSocket` it can easily be migrated to TLS secured ones by just replacing the socket class w/ `cTlsSocket`.

**Comment by dragokas** [comment]
I see, thanks. 
Unfortunately, I didn't yet have practice with old known socket control. But, I see the reason :) +1

However, what if the main thread busy with some time-consuming operation, let's say 1 sec (or some amount of time > timeout), and during this time net packet is incoming? Does user control version have a benefit in such case? I didn't test yet this case, though.

**Comment by wqweto** [comment]
When main UI thread is busy no socket events can be received on this main UI thread so communication is paused until main thread can pump messages (becomes available) again. There is no difference in this behavior between MS Winsock controll, cAsyncSocket class and ctxWinsock replacement control.

**Comment by dragokas** [comment]
Updated GET samples.
Thanks a lot for your detailed explanation in PM.

[Winsock-simple.zip](https://github.com/wqweto/VbAsyncSocket/files/5305716/Winsock-simple.zip)

![test-GET](https://user-images.githubusercontent.com/19956568/94689637-cb127080-0337-11eb-8b01-952ff1672dd1.png)

Remains to do a fix for HTTPS to make it work...

**Comment by wqweto** [comment]
In `ctxWinsock_DataArrival` you don't need `ctxWinsock.PeekData sBuffer` before call to actual `GetData` method.

The `PeekData` method only peeks at recv buffer without removing the data from recv buffer. It is left in sample probably because I've been debugging it. Sorry about that!

**Comment by wqweto** [comment]
Project added under `samples` directory in 4dc96d32677ef7f473d180b922a6ab543647683e

10x!
